# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1217, 803)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.videoPlayer = phonon.Phonon.VideoPlayer(self.frame_2)
        self.videoPlayer.setMinimumSize(QtCore.QSize(640, 360))
        self.videoPlayer.setObjectName(_fromUtf8("videoPlayer"))
        self.gridLayout_2.addWidget(self.videoPlayer, 0, 0, 1, 4)
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setMinimumSize(QtCore.QSize(640, 360))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 4, 1, 1)
        self.seekSlider = phonon.Phonon.SeekSlider(self.frame_2)
        self.seekSlider.setMaximumSize(QtCore.QSize(16777215, 80))
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.gridLayout_2.addWidget(self.seekSlider, 1, 0, 1, 4)
        self.btnPlay = QtGui.QPushButton(self.frame_2)
        self.btnPlay.setObjectName(_fromUtf8("btnPlay"))
        self.gridLayout_2.addWidget(self.btnPlay, 2, 0, 1, 1)
        self.btnPause = QtGui.QPushButton(self.frame_2)
        self.btnPause.setObjectName(_fromUtf8("btnPause"))
        self.gridLayout_2.addWidget(self.btnPause, 2, 1, 1, 1)
        self.btnStop = QtGui.QPushButton(self.frame_2)
        self.btnStop.setObjectName(_fromUtf8("btnStop"))
        self.gridLayout_2.addWidget(self.btnStop, 2, 2, 1, 1)
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.frame_2)
        self.volumeSlider.setMaximumSize(QtCore.QSize(150, 16777215))
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.gridLayout_2.addWidget(self.volumeSlider, 2, 3, 1, 1)
        self.btnPlaywithtext = QtGui.QPushButton(self.frame_2)
        self.btnPlaywithtext.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnPlaywithtext.setObjectName(_fromUtf8("btnPlaywithtext"))
        self.gridLayout_2.addWidget(self.btnPlaywithtext, 2, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 3)
        self.line = QtGui.QFrame(self.frame)
        self.line.setMinimumSize(QtCore.QSize(0, 50))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 1, 0, 1, 3)
        self.btnGeneratetext = QtGui.QPushButton(self.frame)
        self.btnGeneratetext.setMinimumSize(QtCore.QSize(200, 0))
        self.btnGeneratetext.setMaximumSize(QtCore.QSize(500, 16777215))
        self.btnGeneratetext.setObjectName(_fromUtf8("btnGeneratetext"))
        self.gridLayout_3.addWidget(self.btnGeneratetext, 2, 0, 1, 1)
        self.progressbar = QtGui.QProgressBar(self.frame)
        self.progressbar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progressbar.setProperty("value", 24)
        self.progressbar.setObjectName(_fromUtf8("progressbar"))
        self.gridLayout_3.addWidget(self.progressbar, 2, 1, 1, 1)
        self.btnCancel = QtGui.QPushButton(self.frame)
        self.btnCancel.setMinimumSize(QtCore.QSize(200, 0))
        self.btnCancel.setMaximumSize(QtCore.QSize(400, 16777215))
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.gridLayout_3.addWidget(self.btnCancel, 2, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1217, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menuAccuracy = QtGui.QMenu(self.menubar)
        self.menuAccuracy.setObjectName(_fromUtf8("menuAccuracy"))
        self.menuType = QtGui.QMenu(self.menubar)
        self.menuType.setObjectName(_fromUtf8("menuType"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionChange_download_path = QtGui.QAction(MainWindow)
        self.actionChange_download_path.setObjectName(_fromUtf8("actionChange_download_path"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.action10 = QtGui.QAction(MainWindow)
        self.action10.setObjectName(_fromUtf8("action10"))
        self.action12 = QtGui.QAction(MainWindow)
        self.action12.setObjectName(_fromUtf8("action12"))
        self.action14 = QtGui.QAction(MainWindow)
        self.action14.setObjectName(_fromUtf8("action14"))
        self.action16 = QtGui.QAction(MainWindow)
        self.action16.setObjectName(_fromUtf8("action16"))
        self.action18 = QtGui.QAction(MainWindow)
        self.action18.setObjectName(_fromUtf8("action18"))
        self.action20 = QtGui.QAction(MainWindow)
        self.action20.setObjectName(_fromUtf8("action20"))
        self.action24 = QtGui.QAction(MainWindow)
        self.action24.setObjectName(_fromUtf8("action24"))
        self.action28 = QtGui.QAction(MainWindow)
        self.action28.setObjectName(_fromUtf8("action28"))
        self.actionLow = QtGui.QAction(MainWindow)
        self.actionLow.setObjectName(_fromUtf8("actionLow"))
        self.actionMedium = QtGui.QAction(MainWindow)
        self.actionMedium.setObjectName(_fromUtf8("actionMedium"))
        self.actionHigh = QtGui.QAction(MainWindow)
        self.actionHigh.setObjectName(_fromUtf8("actionHigh"))
        self.actionPytesseract = QtGui.QAction(MainWindow)
        self.actionPytesseract.setObjectName(_fromUtf8("actionPytesseract"))
        self.actionML = QtGui.QAction(MainWindow)
        self.actionML.setObjectName(_fromUtf8("actionML"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionChange_download_path)
        self.menuFile.addAction(self.actionExit)
        self.menuSetting.addAction(self.action10)
        self.menuSetting.addAction(self.action12)
        self.menuSetting.addAction(self.action14)
        self.menuSetting.addAction(self.action16)
        self.menuSetting.addAction(self.action18)
        self.menuSetting.addAction(self.action20)
        self.menuSetting.addAction(self.action24)
        self.menuSetting.addAction(self.action28)
        self.menuAccuracy.addAction(self.actionLow)
        self.menuAccuracy.addAction(self.actionMedium)
        self.menuAccuracy.addAction(self.actionHigh)
        self.menuType.addAction(self.actionPytesseract)
        self.menuType.addAction(self.actionML)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAccuracy.menuAction())
        self.menubar.addAction(self.menuType.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.btnPlay.setText(_translate("MainWindow", "Play", None))
        self.btnPause.setText(_translate("MainWindow", "Pause", None))
        self.btnStop.setText(_translate("MainWindow", "Stop", None))
        self.btnPlaywithtext.setText(_translate("MainWindow", "Play with text", None))
        self.btnGeneratetext.setText(_translate("MainWindow", "Generate Text", None))
        self.btnCancel.setText(_translate("MainWindow", "Cancel", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSetting.setTitle(_translate("MainWindow", "Font size", None))
        self.menuAccuracy.setTitle(_translate("MainWindow", "Accuracy", None))
        self.menuType.setTitle(_translate("MainWindow", "Model", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionChange_download_path.setText(_translate("MainWindow", "Change download path", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.action10.setText(_translate("MainWindow", "10", None))
        self.action12.setText(_translate("MainWindow", "12", None))
        self.action14.setText(_translate("MainWindow", "14", None))
        self.action16.setText(_translate("MainWindow", "16", None))
        self.action18.setText(_translate("MainWindow", "18", None))
        self.action20.setText(_translate("MainWindow", "20", None))
        self.action24.setText(_translate("MainWindow", "24", None))
        self.action28.setText(_translate("MainWindow", "28", None))
        self.actionLow.setText(_translate("MainWindow", "Low", None))
        self.actionMedium.setText(_translate("MainWindow", "Medium", None))
        self.actionHigh.setText(_translate("MainWindow", "High", None))
        self.actionPytesseract.setText(_translate("MainWindow", "Pytesseract", None))
        self.actionML.setText(_translate("MainWindow", "ML", None))

from PyQt4 import phonon
